package net.fuzzycraft.botanichorizons.patches;

public class TodoPatches {}

/*
tile.botania:altar0.name=Petal Apothecary
tile.botania:altar1.name=Forest Petal Apothecary
tile.botania:altar2.name=Plains Petal Apothecary
tile.botania:altar3.name=Mountain Petal Apothecary
tile.botania:altar4.name=Fungal Petal Apothecary
tile.botania:altar5.name=Swamp Petal Apothecary
tile.botania:altar6.name=Desert Petal Apothecary
tile.botania:altar7.name=Taiga Petal Apothecary
tile.botania:altar8.name=Mesa Petal Apothecary
tile.botania:livingrock0.name=Livingrock
tile.botania:livingrock1.name=Livingrock Brick
tile.botania:livingrock2.name=Mossy Livingrock Brick
tile.botania:livingrock3.name=Cracked Livingrock Brick
tile.botania:livingrock4.name=Chiseled Livingrock Brick
tile.botania:livingwood0.name=Livingwood
tile.botania:livingwood1.name=Livingwood Planks
tile.botania:livingwood2.name=Mossy Livingwood Planks
tile.botania:livingwood3.name=Framed Livingwood
tile.botania:livingwood4.name=Pattern Framed Livingwood
tile.botania:livingwood5.name=Glimmering Livingwood
tile.botania:spreader0.name=Mana Spreader
tile.botania:spreader1.name=Pulse Mana Spreader
tile.botania:spreader2.name=Elven Mana Spreader
tile.botania:spreader3.name=Gaia Mana Spreader
tile.botania:pool0.name=Mana Pool
tile.botania:pool1.name=The Everlasting Guilty Pool
tile.botania:pool2.name=Diluted Mana Pool
tile.botania:pool3.name=Fabulous Mana Pool
tile.botania:runeAltar.name=Runic Altar
tile.botania:unstableBlock0.name=White Unstable Cube
tile.botania:unstableBlock1.name=Orange Unstable Cube
tile.botania:unstableBlock2.name=Magenta Unstable Cube
tile.botania:unstableBlock3.name=Light Blue Unstable Cube
tile.botania:unstableBlock4.name=Yellow Unstable Cube
tile.botania:unstableBlock5.name=Lime Unstable Cube
tile.botania:unstableBlock6.name=Pink Unstable Cube
tile.botania:unstableBlock7.name=Gray Unstable Cube
tile.botania:unstableBlock8.name=Light Gray Unstable Cube
tile.botania:unstableBlock9.name=Cyan Unstable Cube
tile.botania:unstableBlock10.name=Purple Unstable Cube
tile.botania:unstableBlock11.name=Blue Unstable Cube
tile.botania:unstableBlock12.name=Brown Unstable Cube
tile.botania:unstableBlock13.name=Green Unstable Cube
tile.botania:unstableBlock14.name=Red Unstable Cube
tile.botania:unstableBlock15.name=Black Unstable Cube
tile.botania:pistonRelay.name=Force Relay
tile.botania:distributor.name=Mana Distributor
tile.botania:pylon0.name=Mana Pylon
tile.botania:pylon1.name=Natura Pylon
tile.botania:pylon2.name=Gaia Pylon
tile.botania:manaBeacon0.name=White Unstable Beacon
tile.botania:manaBeacon1.name=Orange Unstable Beacon
tile.botania:manaBeacon2.name=Magenta Unstable Beacon
tile.botania:manaBeacon3.name=Light Blue Unstable Beacon
tile.botania:manaBeacon4.name=Yellow Unstable Beacon
tile.botania:manaBeacon5.name=Lime Unstable Beacon
tile.botania:manaBeacon6.name=Pink Unstable Beacon
tile.botania:manaBeacon7.name=Gray Unstable Beacon
tile.botania:manaBeacon8.name=Light Gray Unstable Beacon
tile.botania:manaBeacon9.name=Cyan Unstable Beacon
tile.botania:manaBeacon10.name=Purple Unstable Beacon
tile.botania:manaBeacon11.name=Blue Unstable Beacon
tile.botania:manaBeacon12.name=Brown Unstable Beacon
tile.botania:manaBeacon13.name=Green Unstable Beacon
tile.botania:manaBeacon14.name=Red Unstable Beacon
tile.botania:manaBeacon15.name=Black Unstable Beacon
tile.botania:manaVoid.name=Mana Void
tile.botania:manaDetector.name=Mana Detector
tile.botania:enchanter.name=Mana Enchanter
tile.botania:turntable.name=Spreader Turntable
tile.botania:tinyPlanetBlock.name=Tiny Planet
tile.botania:alchemyCatalyst.name=Alchemy Catalyst
tile.botania:openCrate0.name=Open Crate
tile.botania:openCrate1.name=Crafty Crate
tile.botania:forestEye.name=Eye of the Ancients
tile.botania:storage0.name=Block of Manasteel
tile.botania:storage1.name=Block of Terrasteel
tile.botania:storage2.name=Block of Elementium
tile.botania:storage3.name=Block of Mana Diamond
tile.botania:storage4.name=Block of Dragonstone
tile.botania:forestDrum0.name=Drum of the Wild
tile.botania:forestDrum1.name=Drum of the Gathering
tile.botania:forestDrum2.name=Drum of the Canopy
tile.botania:shinyFlower0.name=Glimmering White Flower
tile.botania:shinyFlower1.name=Glimmering Orange Flower
tile.botania:shinyFlower2.name=Glimmering Magenta Flower
tile.botania:shinyFlower3.name=Glimmering Light Blue Flower
tile.botania:shinyFlower4.name=Glimmering Yellow Flower
tile.botania:shinyFlower5.name=Glimmering Lime Flower
tile.botania:shinyFlower6.name=Glimmering Pink Flower
tile.botania:shinyFlower7.name=Glimmering Gray Flower
tile.botania:shinyFlower8.name=Glimmering Light Gray Flower
tile.botania:shinyFlower9.name=Glimmering Cyan Flower
tile.botania:shinyFlower10.name=Glimmering Purple Flower
tile.botania:shinyFlower11.name=Glimmering Blue Flower
tile.botania:shinyFlower12.name=Glimmering Brown Flower
tile.botania:shinyFlower13.name=Glimmering Green Flower
tile.botania:shinyFlower14.name=Glimmering Red Flower
tile.botania:shinyFlower15.name=Glimmering Black Flower
tile.botania:platform0.name=Abstruse Platform
tile.botania:platform1.name=Spectral Platform
tile.botania:platform2.name=Infrangible Platform
tile.botania:alfheimPortal.name=Elven Gateway Core
tile.botania:blockDarkQuartz.name=Block of Smokey Quartz
tile.botania:chiseledDarkQuartz.name=Chiseled Smokey Quartz Block
tile.botania:pillarDarkQuartz.name=Pillar Smokey Quartz Block
tile.botania:quartzSlabDarkHalf.name=Smokey Quartz Slab
tile.botania:quartzSlabDarkFull.name=Smokey Quartz Slab
tile.botania:quartzStairsDark.name=Smokey Quartz Stairs
tile.botania:blockManaQuartz.name=Block of Mana Quartz
tile.botania:chiseledManaQuartz.name=Chiseled Mana Quartz Block
tile.botania:pillarManaQuartz.name=Pillar Mana Quartz Block
tile.botania:quartzSlabManaHalf.name=Mana Quartz Slab
tile.botania:quartzSlabManaFull.name=Mana Quartz Slab
tile.botania:quartzStairsMana.name=Mana Quartz Stairs
tile.botania:blockBlazeQuartz.name=Block of Blaze Quartz
tile.botania:chiseledBlazeQuartz.name=Chiseled Blaze Quartz Block
tile.botania:pillarBlazeQuartz.name=Pillar Blaze Quartz Block
tile.botania:quartzSlabBlazeHalf.name=Blaze Quartz Slab
tile.botania:quartzSlabBlazeFull.name=Blaze Quartz Slab
tile.botania:quartzStairsBlaze.name=Blaze Quartz Stairs
tile.botania:blockLavenderQuartz.name=Block of Lavender Quartz
tile.botania:chiseledLavenderQuartz.name=Chiseled Lavender Quartz Block
tile.botania:pillarLavenderQuartz.name=Pillar Lavender Quartz Block
tile.botania:quartzSlabLavenderHalf.name=Lavender Quartz Slab
tile.botania:quartzSlabLavenderFull.name=Lavender Quartz Slab
tile.botania:quartzStairsLavender.name=Lavender Quartz Stairs
tile.botania:blockRedQuartz.name=Block of Redquartz
tile.botania:chiseledRedQuartz.name=Chiseled Redquartz Block
tile.botania:pillarRedQuartz.name=Pillar Redquartz Block
tile.botania:quartzSlabRedHalf.name=Redquartz Slab
tile.botania:quartzSlabRedFull.name=Redquartz Slab
tile.botania:quartzStairsRed.name=Redquartz Stairs
tile.botania:blockElfQuartz.name=Block of Elven Quartz
tile.botania:chiseledElfQuartz.name=Chiseled Elven Quartz Block
tile.botania:pillarElfQuartz.name=Pillar Elven Quartz Block
tile.botania:quartzSlabElfHalf.name=Elven Quartz Slab
tile.botania:quartzSlabElfFull.name=Elven Quartz Slab
tile.botania:quartzStairsElf.name=Elven Quartz Stairs
tile.botania:blockSunnyQuartz.name=Block of Sunny Quartz
tile.botania:chiseledSunnyQuartz.name=Chiseled Sunny Quartz Block
tile.botania:pillarSunnyQuartz.name=Pillar Sunny Quartz Block
tile.botania:quartzSlabSunnyHalf.name=Sunny Quartz Slab
tile.botania:quartzSlabSunnyFull.name=Sunny Quartz Slab
tile.botania:quartzStairsSunny.name=Sunny Quartz Stairs
tile.botania:dreamwood0.name=Dreamwood
tile.botania:dreamwood1.name=Dreamwood Planks
tile.botania:dreamwood2.name=Mossy Dreamwood Planks
tile.botania:dreamwood3.name=Framed Dreamwood
tile.botania:dreamwood4.name=Pattern Framed Dreamwood
tile.botania:dreamwood5.name=Glimmering Dreamwood
tile.botania:livingwood0Stairs.name=Livingwood Stairs
tile.botania:livingwood0Slab.name=Livingwood Slab
tile.botania:livingwood0SlabFull.name=Livingwood Slab
tile.botania:livingwood1Stairs.name=Livingwood Plank Stairs
tile.botania:livingwood1Slab.name=Livingwood Plank Slab
tile.botania:livingwood1SlabFull.name=Livingwood Plank Slab
tile.botania:livingrock0Stairs.name=Livingrock Stairs
tile.botania:livingrock0Slab.name=Livingrock Slab
tile.botania:livingrock0SlabFull.name=Livingrock Slab
tile.botania:livingrock1Stairs.name=Livingrock Brick Stairs
tile.botania:livingrock1Slab.name=Livingrock Brick Slab
tile.botania:livingrock1SlabFull.name=Livingrock Brick Slab
tile.botania:dreamwood0Stairs.name=Dreamwood Stairs
tile.botania:dreamwood0Slab.name=Dreamwood Slab
tile.botania:dreamwood0SlabFull.name=Dreamwood Slab
tile.botania:dreamwood1Stairs.name=Dreamwood Plank Stairs
tile.botania:dreamwood1Slab.name=Dreamwood Plank Slab
tile.botania:dreamwood1SlabFull.name=Dreamwood Plank Slab
tile.botania:conjurationCatalyst.name=Conjuration Catalyst
tile.botania:prismarine0.name=Prismarine
tile.botania:prismarine1.name=Prismarine Bricks
tile.botania:prismarine2.name=Dark Prismarine
tile.botania:prismarine0Stairs.name=Prismarine Stairs
tile.botania:prismarine0Slab.name=Prismarine Slab
tile.botania:prismarine0SlabFull.name=Prismarine Slab
tile.botania:prismarine1Stairs.name=Prismarine Brick Stairs
tile.botania:prismarine1Slab.name=Prismarine Brick Slab
tile.botania:prismarine1SlabFull.name=Prismarine Brick Slab
tile.botania:prismarine2Stairs.name=Dark Prismarine Stairs
tile.botania:prismarine2Slab.name=Dark Prismarine Slab
tile.botania:prismarine2SlabFull.name=Dark Prismarine Slab
tile.botania:seaLamp.name=Sea Lantern
tile.botania:miniIsland0.name=Floating White Flower
tile.botania:miniIsland1.name=Floating Orange Flower
tile.botania:miniIsland2.name=Floating Magenta Flower
tile.botania:miniIsland3.name=Floating Light Blue Flower
tile.botania:miniIsland4.name=Floating Yellow Flower
tile.botania:miniIsland5.name=Floating Lime Flower
tile.botania:miniIsland6.name=Floating Pink Flower
tile.botania:miniIsland7.name=Floating Gray Flower
tile.botania:miniIsland8.name=Floating Light Gray Flower
tile.botania:miniIsland9.name=Floating Cyan Flower
tile.botania:miniIsland10.name=Floating Purple Flower
tile.botania:miniIsland11.name=Floating Blue Flower
tile.botania:miniIsland12.name=Floating Brown Flower
tile.botania:miniIsland13.name=Floating Green Flower
tile.botania:miniIsland14.name=Floating Red Flower
tile.botania:miniIsland15.name=Floating Black Flower
tile.botania:tinyPotato.name=Tiny Potato
tile.botania:spawnerClaw.name=Life Imbuer
tile.botania:reedBlock.name=Reed Block
tile.botania:reedBlock0Stairs.name=Reed Stairs
tile.botania:reedBlock0Slab.name=Reed Slab
tile.botania:reedBlock0SlabFull.name=Reed Slab
tile.botania:thatch.name=Thatch
tile.botania:thatch0Stairs.name=Thatch Stairs
tile.botania:thatch0Slab.name=Thatch Slab
tile.botania:thatch0SlabFull.name=Thatch Slab
tile.botania:customBrick0.name=Hellish Brick
tile.botania:customBrick1.name=Soul Brick
tile.botania:customBrick2.name=Frosty Brick
tile.botania:customBrick3.name=Roof Tile
tile.botania:customBrick0Stairs.name=Hellish Brick Stairs
tile.botania:customBrick1Stairs.name=Soul Brick Stairs
tile.botania:customBrick2Stairs.name=Frosty Brick Stairs
tile.botania:customBrick3Stairs.name=Roof Tile Stairs
tile.botania:customBrick0Slab.name=Hellish Brick Slab
tile.botania:customBrick0SlabFull.name=Hellish Brick Slab
tile.botania:customBrick1Slab.name=Soul Brick Slab
tile.botania:customBrick1SlabFull.name=Soul Brick Slab
tile.botania:customBrick2Slab.name=Frosty Brick Slab
tile.botania:customBrick2SlabFull.name=Frosty Brick Slab
tile.botania:customBrick3Slab.name=Roof Tile Slab
tile.botania:customBrick3SlabFull.name=Roof Tile Slab
tile.botania:customBrick4.name=Azulejo
tile.botania:customBrick5.name=Azulejo
tile.botania:customBrick6.name=Azulejo
tile.botania:customBrick7.name=Azulejo
tile.botania:customBrick8.name=Azulejo
tile.botania:customBrick9.name=Azulejo
tile.botania:customBrick10.name=Azulejo
tile.botania:customBrick11.name=Azulejo
tile.botania:customBrick12.name=Azulejo
tile.botania:customBrick13.name=Azulejo
tile.botania:customBrick14.name=Azulejo
tile.botania:customBrick15.name=Azulejo
tile.botania:enderEyeBlock.name=Ender Overseer
tile.botania:starfield.name=Starfield Creator
tile.botania:rfGenerator.name=Mana Fluxfield
tile.botania:elfGlass.name=Alfglass
tile.botania:brewery.name=Botanical Brewery
tile.botania:manaGlass.name=Managlass
tile.botania:terraPlate.name=Terrestrial Agglomeration Plate
tile.botania:redStringContainer.name=Red Stringed Container
tile.botania:redStringDispenser.name=Red Stringed Dispenser
tile.botania:redStringFertilizer.name=Red Stringed Nutrifier
tile.botania:redStringComparator.name=Red Stringed Comparator
tile.botania:redStringRelay.name=Red Stringed Spoofer
tile.botania:redStringInterceptor.name=Red Stringed Interceptor
tile.botania:manaFlame.name=Mana Flash
tile.botania:prism.name=Mana Prism
tile.botania:dirtPath.name=Trodden Dirt
tile.botania:enchantedSoil.name=Enchanted Soil
tile.botania:dirtPath0Slab.name=Trodden Dirt Slab
tile.botania:dirtPath0SlabFull.name=Trodden Dirt Slab
tile.botania:biomeStoneA0.name=Metamorphic Forest Stone
tile.botania:biomeStoneA1.name=Metamorphic Plains Stone
tile.botania:biomeStoneA2.name=Metamorphic Mountain Stone
tile.botania:biomeStoneA3.name=Metamorphic Fungal Stone
tile.botania:biomeStoneA4.name=Metamorphic Swamp Stone
tile.botania:biomeStoneA5.name=Metamorphic Desert Stone
tile.botania:biomeStoneA6.name=Metamorphic Taiga Stone
tile.botania:biomeStoneA7.name=Metamorphic Mesa Stone
tile.botania:biomeStoneA8.name=Metamorphic Forest Cobblestone
tile.botania:biomeStoneA9.name=Metamorphic Plains Cobblestone
tile.botania:biomeStoneA10.name=Metamorphic Mountain Cobblestone
tile.botania:biomeStoneA11.name=Metamorphic Fungal Cobblestone
tile.botania:biomeStoneA12.name=Metamorphic Swamp Cobblestone
tile.botania:biomeStoneA13.name=Metamorphic Desert Cobblestone
tile.botania:biomeStoneA14.name=Metamorphic Taiga Cobblestone
tile.botania:biomeStoneA15.name=Metamorphic Mesa Cobblestone
tile.botania:biomeStoneB0.name=Metamorphic Forest Stone Bricks
tile.botania:biomeStoneB1.name=Metamorphic Plains Stone Bricks
tile.botania:biomeStoneB2.name=Metamorphic Mountain Stone Bricks
tile.botania:biomeStoneB3.name=Metamorphic Fungal Stone Bricks
tile.botania:biomeStoneB4.name=Metamorphic Swamp Stone Bricks
tile.botania:biomeStoneB5.name=Metamorphic Desert Stone Bricks
tile.botania:biomeStoneB6.name=Metamorphic Taiga Stone Bricks
tile.botania:biomeStoneB7.name=Metamorphic Mesa Stone Bricks
tile.botania:biomeStoneB8.name=Chiseled Metamorphic Forest Stone Brick
tile.botania:biomeStoneB9.name=Chiseled Metamorphic Plains Stone Brick
tile.botania:biomeStoneB10.name=Chiseled Metamorphic Mountain Stone Brick
tile.botania:biomeStoneB11.name=Chiseled Metamorphic Fungal Stone Brick
tile.botania:biomeStoneB12.name=Chiseled Metamorphic Swamp Stone Brick
tile.botania:biomeStoneB13.name=Chiseled Metamorphic Desert Stone Brick
tile.botania:biomeStoneB14.name=Chiseled Metamorphic Taiga Stone Brick
tile.botania:biomeStoneB15.name=Chiseled Metamorphic Mesa Stone Brick
tile.botania:biomeStoneA0Stairs.name=Metamorphic Forest Stone Stairs
tile.botania:biomeStoneA1Stairs.name=Metamorphic Plains Stone Stairs
tile.botania:biomeStoneA2Stairs.name=Metamorphic Mountain Stone Stairs
tile.botania:biomeStoneA3Stairs.name=Metamorphic Fungal Stone Stairs
tile.botania:biomeStoneA4Stairs.name=Metamorphic Swamp Stone Stairs
tile.botania:biomeStoneA5Stairs.name=Metamorphic Desert Stone Stairs
tile.botania:biomeStoneA6Stairs.name=Metamorphic Taiga Stone Stairs
tile.botania:biomeStoneA7Stairs.name=Metamorphic Mesa Stone Stairs
tile.botania:biomeStoneA8Stairs.name=Metamorphic Forest Cobblestone Stairs
tile.botania:biomeStoneA9Stairs.name=Metamorphic Plains Cobblestone Stairs
tile.botania:biomeStoneA10Stairs.name=Metamorphic Mountain Cobblestone Stairs
tile.botania:biomeStoneA11Stairs.name=Metamorphic Fungal Cobblestone Stairs
tile.botania:biomeStoneA12Stairs.name=Metamorphic Swamp Cobblestone Stairs
tile.botania:biomeStoneA13Stairs.name=Metamorphic Desert Cobblestone Stairs
tile.botania:biomeStoneA14Stairs.name=Metamorphic Taiga Cobblestone Stairs
tile.botania:biomeStoneA15Stairs.name=Metamorphic Mesa Cobblestone Stairs
tile.botania:biomeStoneB0Stairs.name=Metamorphic Forest Stone Brick Stairs
tile.botania:biomeStoneB1Stairs.name=Metamorphic Plains Stone Brick Stairs
tile.botania:biomeStoneB2Stairs.name=Metamorphic Mountain Stone Brick Stairs
tile.botania:biomeStoneB3Stairs.name=Metamorphic Fungal Stone Brick Stairs
tile.botania:biomeStoneB4Stairs.name=Metamorphic Swamp Stone Brick Stairs
tile.botania:biomeStoneB5Stairs.name=Metamorphic Desert Stone Brick Stairs
tile.botania:biomeStoneB6Stairs.name=Metamorphic Taiga Stone Brick Stairs
tile.botania:biomeStoneB7Stairs.name=Metamorphic Mesa Stone Bricks Stairs
tile.botania:biomeStoneA0Slab.name=Metamorphic Forest Stone Slab
tile.botania:biomeStoneA1Slab.name=Metamorphic Plains Stone Slab
tile.botania:biomeStoneA2Slab.name=Metamorphic Mountain Stone Slab
tile.botania:biomeStoneA3Slab.name=Metamorphic Fungal Stone Slab
tile.botania:biomeStoneA4Slab.name=Metamorphic Swamp Stone Slab
tile.botania:biomeStoneA5Slab.name=Metamorphic Desert Stone Slab
tile.botania:biomeStoneA6Slab.name=Metamorphic Taiga Stone Slab
tile.botania:biomeStoneA7Slab.name=Metamorphic Mesa Stone Slab
tile.botania:biomeStoneA8Slab.name=Metamorphic Forest Cobblestone Slab
tile.botania:biomeStoneA9Slab.name=Metamorphic Plains Cobblestone Slab
tile.botania:biomeStoneA10Slab.name=Metamorphic Mountain Cobblestone Slab
tile.botania:biomeStoneA11Slab.name=Metamorphic Fungal Cobblestone Slab
tile.botania:biomeStoneA12Slab.name=Metamorphic Swamp Cobblestone Slab
tile.botania:biomeStoneA13Slab.name=Metamorphic Desert Cobblestone Slab
tile.botania:biomeStoneA14Slab.name=Metamorphic Taiga Cobblestone Slab
tile.botania:biomeStoneA15Slab.name=Metamorphic Mesa Cobblestone Slab
tile.botania:biomeStoneB0Slab.name=Metamorphic Forest Stone Brick Slab
tile.botania:biomeStoneB1Slab.name=Metamorphic Plains Stone Brick Slab
tile.botania:biomeStoneB2Slab.name=Metamorphic Mountain Stone Brick Slab
tile.botania:biomeStoneB3Slab.name=Metamorphic Fungal Stone Brick Slab
tile.botania:biomeStoneB4Slab.name=Metamorphic Swamp Stone Brick Slab
tile.botania:biomeStoneB5Slab.name=Metamorphic Desert Stone Brick Slab
tile.botania:biomeStoneB6Slab.name=Metamorphic Taiga Stone Brick Slab
tile.botania:biomeStoneB7Slab.name=Metamorphic Mesa Stone Bricks Slab
tile.botania:biomeStoneA0SlabFull.name=Metamorphic Forest Stone Slab
tile.botania:biomeStoneA1SlabFull.name=Metamorphic Plains Stone Slab
tile.botania:biomeStoneA2SlabFull.name=Metamorphic Mountain Stone Slab
tile.botania:biomeStoneA3SlabFull.name=Metamorphic Fungal Stone Slab
tile.botania:biomeStoneA4SlabFull.name=Metamorphic Swamp Stone Slab
tile.botania:biomeStoneA5SlabFull.name=Metamorphic Desert Stone Slab
tile.botania:biomeStoneA6SlabFull.name=Metamorphic Taiga Stone Slab
tile.botania:biomeStoneA7SlabFull.name=Metamorphic Mesa Stone Slab
tile.botania:biomeStoneA8SlabFull.name=Metamorphic Forest Cobblestone Slab
tile.botania:biomeStoneA9SlabFull.name=Metamorphic Plains Cobblestone Slab
tile.botania:biomeStoneA10SlabFull.name=Metamorphic Mountain Cobblestone Slab
tile.botania:biomeStoneA11SlabFull.name=Metamorphic Fungal Cobblestone Slab
tile.botania:biomeStoneA12SlabFull.name=Metamorphic Swamp Cobblestone Slab
tile.botania:biomeStoneA13SlabFull.name=Metamorphic Desert Cobblestone Slab
tile.botania:biomeStoneA14SlabFull.name=Metamorphic Taiga Cobblestone Slab
tile.botania:biomeStoneA15SlabFull.name=Metamorphic Mesa Cobblestone Slab
tile.botania:biomeStoneB0SlabFull.name=Metamorphic Forest Stone Brick Slab
tile.botania:biomeStoneB1SlabFull.name=Metamorphic Plains Stone Brick Slab
tile.botania:biomeStoneB2SlabFull.name=Metamorphic Mountain Stone Brick Slab
tile.botania:biomeStoneB3SlabFull.name=Metamorphic Fungal Stone Brick Slab
tile.botania:biomeStoneB4SlabFull.name=Metamorphic Swamp Stone Brick Slab
tile.botania:biomeStoneB5SlabFull.name=Metamorphic Desert Stone Brick Slab
tile.botania:biomeStoneB6SlabFull.name=Metamorphic Taiga Stone Brick Slab
tile.botania:biomeStoneB7SlabFull.name=Metamorphic Mesa Stone Bricks Slab
tile.botania:corporeaIndex.name=Corporea Index
tile.botania:corporeaFunnel.name=Corporea Funnel
tile.botania:endStoneBrick0.name=End Stone Bricks
tile.botania:endStoneBrick1.name=Chiseled End Stone Brick
tile.botania:endStoneBrick2.name=Ender Bricks
tile.botania:endStoneBrick3.name=Pillar Ender Bricks
tile.botania:endStoneBrick0Slab.name=End Stone Brick Slab
tile.botania:endStoneBrick0SlabFull.name=End Stone Brick Slab
tile.botania:endStoneBrick0Stairs.name=End Stone Brick Stairs
tile.botania:endStoneBrick2Slab.name=Ender Brick Slab
tile.botania:endStoneBrick2SlabFull.name=Ender Brick Slab
tile.botania:endStoneBrick2Stairs.name=Ender Brick Stairs
tile.botania:mushroom0.name=White Shimmering Mushroom
tile.botania:mushroom1.name=Orange Shimmering Mushroom
tile.botania:mushroom2.name=Magenta Shimmering Mushroom
tile.botania:mushroom3.name=Light Blue Shimmering Mushroom
tile.botania:mushroom4.name=Yellow Shimmering Mushroom
tile.botania:mushroom5.name=Lime Shimmering Mushroom
tile.botania:mushroom6.name=Pink Shimmering Mushroom
tile.botania:mushroom7.name=Gray Shimmering Mushroom
tile.botania:mushroom8.name=Light Gray Shimmering Mushroom
tile.botania:mushroom9.name=Cyan Shimmering Mushroom
tile.botania:mushroom10.name=Purple Shimmering Mushroom
tile.botania:mushroom11.name=Blue Shimmering Mushroom
tile.botania:mushroom12.name=Brown Shimmering Mushroom
tile.botania:mushroom13.name=Green Shimmering Mushroom
tile.botania:mushroom14.name=Red Shimmering Mushroom
tile.botania:mushroom15.name=Black Shimmering Mushroom
tile.botania:pump.name=Mana Pump
tile.botania:doubleFlower10.name=Tall Mystical White Flower
tile.botania:doubleFlower11.name=Tall Mystical Orange Flower
tile.botania:doubleFlower12.name=Tall Mystical Magenta Flower
tile.botania:doubleFlower13.name=Tall Mystical Light Blue Flower
tile.botania:doubleFlower14.name=Tall Mystical Yellow Flower
tile.botania:doubleFlower15.name=Tall Mystical Lime Flower
tile.botania:doubleFlower16.name=Tall Mystical Pink Flower
tile.botania:doubleFlower17.name=Tall Mystical Gray Flower
tile.botania:doubleFlower20.name=Tall Mystical Light Gray Flower
tile.botania:doubleFlower21.name=Tall Mystical Cyan Flower
tile.botania:doubleFlower22.name=Tall Mystical Purple Flower
tile.botania:doubleFlower23.name=Tall Mystical Blue Flower
tile.botania:doubleFlower24.name=Tall Mystical Brown Flower
tile.botania:doubleFlower25.name=Tall Mystical Green Flower
tile.botania:doubleFlower26.name=Tall Mystical Red Flower
tile.botania:doubleFlower27.name=Tall Mystical Black Flower
tile.botania:doubleFlower18.name=Tall Mystical White Flower
tile.botania:doubleFlower19.name=Tall Mystical Orange Flower
tile.botania:doubleFlower110.name=Tall Mystical Magenta Flower
tile.botania:doubleFlower111.name=Tall Mystical Light Blue Flower
tile.botania:doubleFlower112.name=Tall Mystical Yellow Flower
tile.botania:doubleFlower113.name=Tall Mystical Lime Flower
tile.botania:doubleFlower114.name=Tall Mystical Pink Flower
tile.botania:doubleFlower115.name=Tall Mystical Gray Flower
tile.botania:doubleFlower28.name=Tall Mystical Light Gray Flower
tile.botania:doubleFlower29.name=Tall Mystical Cyan Flower
tile.botania:doubleFlower210.name=Tall Mystical Purple Flower
tile.botania:doubleFlower211.name=Tall Mystical Blue Flower
tile.botania:doubleFlower212.name=Tall Mystical Brown Flower
tile.botania:doubleFlower213.name=Tall Mystical Green Flower
tile.botania:doubleFlower214.name=Tall Mystical Red Flower
tile.botania:doubleFlower215.name=Tall Mystical Black Flower
tile.botania:stone0.name=Andesite
tile.botania:stone1.name=Basalt
tile.botania:stone2.name=Diorite
tile.botania:stone3.name=Granite
tile.botania:stone4.name=Polished Andesite
tile.botania:stone5.name=Polished Basalt
tile.botania:stone6.name=Polished Diorite
tile.botania:stone7.name=Polished Granite
tile.botania:stone8.name=Andesite Bricks
tile.botania:stone9.name=Basalt Bricks
tile.botania:stone10.name=Diorite Bricks
tile.botania:stone11.name=Granite Bricks
tile.botania:stone12.name=Chiseled Andesite Brick
tile.botania:stone13.name=Chiseled Basalt Brick
tile.botania:stone14.name=Chiseled Diorite Brick
tile.botania:stone15.name=Chiseled Granite Brick
tile.botania:stone0Stairs.name=Andesite Stairs
tile.botania:stone1Stairs.name=Basalt Stairs
tile.botania:stone2Stairs.name=Diorite Stairs
tile.botania:stone3Stairs.name=Granite Stairs
tile.botania:stone8Stairs.name=Andesite Brick Stairs
tile.botania:stone9Stairs.name=Basalt Brick Stairs
tile.botania:stone10Stairs.name=Diorite Brick Stairs
tile.botania:stone11Stairs.name=Granite Brick Stairs
tile.botania:stone0Slab.name=Andesite Slab
tile.botania:stone1Slab.name=Basalt Slab
tile.botania:stone2Slab.name=Diorite Slab
tile.botania:stone3Slab.name=Granite Slab
tile.botania:stone8Slab.name=Andesite Brick Slab
tile.botania:stone9Slab.name=Basalt Brick Slab
tile.botania:stone10Slab.name=Diorite Brick Slab
tile.botania:stone11Slab.name=Granite Brick Slab
tile.botania:stone0SlabFull.name=Andesite Slab
tile.botania:stone1SlabFull.name=Basalt Slab
tile.botania:stone2SlabFull.name=Diorite Slab
tile.botania:stone3SlabFull.name=Granite Slab
tile.botania:stone8SlabFull.name=Andesite Brick Slab
tile.botania:stone9SlabFull.name=Basalt Brick Slab
tile.botania:stone10SlabFull.name=Diorite Brick Slab
tile.botania:stone11SlabFull.name=Granite Brick Slab
tile.botania:blazeBlock.name=Blaze Lamp
tile.botania:corporeaInterceptor.name=Corporea Interceptor
tile.botania:corporeaCrystalCube.name=Corporea Crystal Cube
tile.botania:incensePlate.name=Incense Plate
tile.botania:hourglass.name=Hovering Hourglass
tile.botania:ghostRail.name=Spectral Rail
tile.botania:sparkChanger.name=Spark Tinkerer
tile.botania:root.name=Living Root
tile.botania:felPumpkin.name=Fel Pumpkin
tile.botania:cocoon.name=Cocoon of Caprice
tile.botania:lightRelay0.name=Luminizer
tile.botania:lightRelay1.name=Detector Luminizer
tile.botania:lightLauncher.name=Luminizer Launcher
tile.botania:livingrock0Wall.name=Livingrock Wall
tile.botania:livingwood0Wall.name=Livingwood Wall
tile.botania:dreamwood0Wall.name=Dreamwood Wall
tile.botania:prismarine0Wall.name=Prismarine Wall
tile.botania:reedBlock0Wall.name=Reed Block Wall
tile.botania:biomeStoneA0Wall0.name=Metamorphic Forest Cobblestone Wall
tile.botania:biomeStoneA0Wall1.name=Metamorphic Plains Cobblestone Wall
tile.botania:biomeStoneA0Wall2.name=Metamorphic Mountain Cobblestone Wall
tile.botania:biomeStoneA0Wall3.name=Metamorphic Fungal Cobblestone Wall
tile.botania:biomeStoneA0Wall4.name=Metamorphic Swamp Cobblestone Wall
tile.botania:biomeStoneA0Wall5.name=Metamorphic Desert Cobblestone Wall
tile.botania:biomeStoneA0Wall6.name=Metamorphic Taiga Cobblestone Wall
tile.botania:biomeStoneA0Wall7.name=Metamorphic Mesa Cobblestone Wall
tile.botania:stone0Wall0.name=Andesite Wall
tile.botania:stone0Wall1.name=Basalt Wall
tile.botania:stone0Wall2.name=Diorite Wall
tile.botania:stone0Wall3.name=Granite Wall
tile.botania:manaBomb.name=Manastorm Charge
tile.botania:buriedPetals0=Buried White Petal
tile.botania:buriedPetals0.name=Buried White Petal
tile.botania:buriedPetals1.name=Buried Orange Petal
tile.botania:buriedPetals2.name=Buried Magenta Petal
tile.botania:buriedPetals3.name=Buried Light Blue Petal
tile.botania:buriedPetals4.name=Buried Yellow Petal
tile.botania:buriedPetals5.name=Buried Lime Petal
tile.botania:buriedPetals6.name=Buried Pink Petal
tile.botania:buriedPetals7.name=Buried Gray Petal
tile.botania:buriedPetals8.name=Buried Light Gray Petal
tile.botania:buriedPetals9.name=Buried Cyan Petal
tile.botania:buriedPetals10.name=Buried Purple Petal
tile.botania:buriedPetals11.name=Buried Blue Petal
tile.botania:buriedPetals12.name=Buried Brown Petal
tile.botania:buriedPetals13.name=Buried Green Petal
tile.botania:buriedPetals14.name=Buried Red Petal
tile.botania:buriedPetals15.name=Buried Black Petal
tile.botania:cacophoniumBlock.name=Cacophonium Block
tile.botania:bellows.name=Manatide Bellows
tile.botania:bifrost.name=Temporary Bifrost Block
tile.botania:bifrostPerm.name=Bifrost Block
tile.botania:pavement0.name=White Portuguese Pavement
tile.botania:pavement1.name=Black Portuguese Pavement
tile.botania:pavement2.name=Blue Portuguese Pavement
tile.botania:pavement3.name=Red Portuguese Pavement
tile.botania:pavement4.name=Yellow Portuguese Pavement
tile.botania:pavement5.name=Green Portuguese Pavement
tile.botania:pavement0Stairs.name=White Portuguese Pavement Stairs
tile.botania:pavement1Stairs.name=Black Portuguese Pavement Stairs
tile.botania:pavement2Stairs.name=Blue Portuguese Pavement Stairs
tile.botania:pavement3Stairs.name=Red Portuguese Pavement Stairs
tile.botania:pavement4Stairs.name=Yellow Portuguese Pavement Stairs
tile.botania:pavement5Stairs.name=Green Portuguese Pavement Stairs
tile.botania:pavement0Slab.name=White Portuguese Pavement Slab
tile.botania:pavement0SlabFull.name=White Portuguese Pavement Slab
tile.botania:pavement1Slab.name=Black Portuguese Pavement Slab
tile.botania:pavement1SlabFull.name=Black Portuguese Pavement Slab
tile.botania:pavement2Slab.name=Blue Portuguese Pavement Slab
tile.botania:pavement2SlabFull.name=Blue Portuguese Pavement Slab
tile.botania:pavement3Slab.name=Red Portuguese Pavement Slab
tile.botania:pavement3SlabFull.name=Red Portuguese Pavement Slab
tile.botania:pavement4Slab.name=Yellow Portuguese Pavement Slab
tile.botania:pavement4SlabFull.name=Yellow Portuguese Pavement Slab
tile.botania:pavement5Slab.name=Green Portuguese Pavement Slab
tile.botania:pavement5SlabFull.name=Green Portuguese Pavement Slab
tile.botania:cellBlock.name=Cellular Block
tile.botania:gaiaHeadBlock.name=Gaia Guardian's Head
tile.botania:corporeaRetainer.name=Corporea Retainer
tile.botania:manaGlassPane.name=Managlass Pane
tile.botania:elfGlassPane.name=Alfglass Pane
tile.botania:bifrostPermPane.name=Bifrost Pane
tile.botania:teruTeruBozu.name=Teru Teru Bozu
tile.botania:shimmerrock.name=Shimmerrock
tile.botania:shimmerrock0Slab.name=Shimmerrock Slab
tile.botania:shimmerrock0SlabFull.name=Shimmerrock Slab
tile.botania:shimmerrock0Stairs.name=Shimmerrock Stairs
tile.botania:shimmerwoodPlanks.name=Shimmerwood Planks
tile.botania:shimmerwoodPlanks0Slab.name=Shimmerwood Plank Slab
tile.botania:shimmerwoodPlanks0SlabFull.name=Shimmerwood Plank Slab
tile.botania:shimmerwoodPlanks0Stairs.name=Shimmerwood Plank Stairs
tile.botania:avatar.name=Livingwood Avatar
tile.botania:altGrass0.name=Dry Grass
tile.botania:altGrass1.name=Golden Grass
tile.botania:altGrass2.name=Vivid Grass
tile.botania:altGrass3.name=Scorched Grass
tile.botania:altGrass4.name=Infused Grass
tile.botania:altGrass5.name=Mutated Grass

tile.botania:flower.puredaisy.name=Pure Daisy
tile.botania:flower.puredaisy.reference=What color do you want to be?
tile.botania:flower.manastar.name=Manastar
tile.botania:flower.manastar.reference=Wish upon a star

# - GENERATING
tile.botania:flower.daybloom.name=Daybloom
tile.botania:flower.daybloom.reference=A Sting of light
tile.botania:flower.daybloomDecor.name=Daybloom Motif
tile.botania:flower.daybloomDecor.reference=A Sting of light
tile.botania:flower.daybloomPrime.name=Daybloom Primus
tile.botania:flower.daybloomPrime.reference=You should not have this on you
tile.botania:flower.endoflame.name=Endoflame
tile.botania:flower.endoflame.reference=Squirting Lag
tile.botania:flower.hydroangeas.name=Hydroangeas
tile.botania:flower.hydroangeas.reference=Just friendly crustaceans
tile.botania:flower.hydroangeasDecor.name=Hydroangeas Motif
tile.botania:flower.hydroangeasDecor.reference=Just friendly crustaceans
tile.botania:flower.thermalily.name=Thermalily
tile.botania:flower.thermalily.reference=A Scarlet Rose indeed
tile.botania:flower.nightshade.name=Nightshade
tile.botania:flower.nightshade.reference=Ghastly signature
tile.botania:flower.nightshadePrime.name=Nightshade Primus
tile.botania:flower.nightshadePrime.reference=You should not have this on you
tile.botania:flower.nightshadeDecor.name=Nightshade Motif
tile.botania:flower.nightshadeDecor.reference=Ghastly signature
tile.botania:flower.arcanerose.name=Rosa Arcana
tile.botania:flower.arcanerose.reference=Ten blue orbs in the corner
tile.botania:flower.munchdew.name=Munchdew
tile.botania:flower.munchdew.reference=Nommy nommy the art teacher
tile.botania:flower.entropinnyum.name=Entropinnyum
tile.botania:flower.entropinnyum.reference=Magical girls are an option
tile.botania:flower.kekimurus.name=Kekimurus
tile.botania:flower.kekimurus.reference=This flower is a lie
tile.botania:flower.gourmaryllis.name=Gourmaryllis
tile.botania:flower.gourmaryllis.reference=Fuyukai Desu
tile.botania:flower.narslimmus.name=Narslimmus
tile.botania:flower.narslimmus.reference=What's this? It's all sticky
tile.botania:flower.spectrolus.name=Spectrolus
tile.botania:flower.spectrolus.reference=Profiting off Hate
tile.botania:flower.dandelifeon.name=Dandelifeon
tile.botania:flower.dandelifeon.reference=C'est la vie
tile.botania:flower.rafflowsia.name=Rafflowsia
tile.botania:flower.rafflowsia.reference=Trap Hole Nightmare

# - FUNCTIONAL
tile.botania:flower.bellethorn.name=Bellethorne
tile.botania:flower.bellethorn.reference=world's end, girl's rondo
tile.botania:flower.bellethornChibi.name=Bellethorne Petite
tile.botania:flower.bellethornChibi.reference=world's end, girl's rondo
tile.botania:flower.dreadthorn.name=Dreadthorne
tile.botania:flower.dreadthorn.reference=Plan C
tile.botania:flower.heiseiDream.name=Heisei Dream
tile.botania:flower.heiseiDream.reference=Heisei heisei kowarete
tile.botania:flower.tigerseye.name=Tigerseye
tile.botania:flower.tigerseye.reference=The palmtop tiger
tile.botania:flower.jadedAmaranthus.name=Jaded Amaranthus
tile.botania:flower.jadedAmaranthus.reference=A couple died for this
tile.botania:flower.orechid.name=Orechid
tile.botania:flower.orechid.reference=I seed what you did there
tile.botania:flower.orechidIgnem.name=Orechid Ignem
tile.botania:flower.orechidIgnem.reference=Red like roses
tile.botania:flower.fallenKanade.name=Fallen Kanade
tile.botania:flower.fallenKanade.reference=I'm not an Angel
tile.botania:flower.exoflame.name=Exoflame
tile.botania:flower.exoflame.reference=Wearing her black ribbons
tile.botania:flower.agricarnation.name=Agricarnation
tile.botania:flower.agricarnation.reference=Wear on the 25th of april
tile.botania:flower.agricarnationChibi.name=Agricarnation Petite
tile.botania:flower.agricarnationChibi.reference=Wear on the 25th of april
tile.botania:flower.hopperhock.name=Hopperhock
tile.botania:flower.hopperhock.reference=It all funnels into it
tile.botania:flower.hopperhockChibi.name=Hopperhock Petite
tile.botania:flower.hopperhockChibi.reference=It all funnels into it
tile.botania:flower.tangleberrie.name=Tangleberrie
tile.botania:flower.tangleberrie.reference=No frying pans allowed
tile.botania:flower.jiyuulia.name=Jiyuulia
tile.botania:flower.jiyuulia.reference=Flügel der Freiheit
tile.botania:flower.rannuncarpus.name=Rannuncarpus
tile.botania:flower.rannuncarpus.reference=That's handy
tile.botania:flower.rannuncarpusChibi.name=Rannuncarpus Petite
tile.botania:flower.rannuncarpusChibi.reference=That's handy
tile.botania:flower.hyacidus.name=Hyacidus
tile.botania:flower.hyacidus.reference=If you don't walk, it doesn't hurt
tile.botania:flower.pollidisiac.name=Pollidisiac
tile.botania:flower.pollidisiac.reference=Birds and bees
tile.botania:flower.clayconia.name=Clayconia
tile.botania:flower.clayconia.reference=Rupees not included
tile.botania:flower.clayconiaChibi.name=Clayconia Petite
tile.botania:flower.clayconiaChibi.reference=Rupees not included
tile.botania:flower.loonium.name=Loonium
tile.botania:flower.loonium.reference=Hold it up above your head
tile.botania:flower.daffomill.name=Daffomill
tile.botania:flower.daffomill.reference=Cook's Assistant
tile.botania:flower.vinculotus.name=Vinculotus
tile.botania:flower.vinculotus.reference=Totally an Extra Utils ripoff
tile.botania:flower.spectranthemum.name=Spectranthemum
tile.botania:flower.spectranthemum.reference=In the shell
tile.botania:flower.medumone.name=Medumone
tile.botania:flower.medumone.reference='Twas Hades all along
tile.botania:flower.marimorphosis.name=Marimorphosis
tile.botania:flower.marimorphosis.reference=U-MA-RU
tile.botania:flower.marimorphosisChibi.name=Marimorphosis Petite
tile.botania:flower.marimorphosisChibi.reference=U-MA-RU
tile.botania:flower.bubbell.name=Bubbell
tile.botania:flower.bubbell.reference=And whistle
tile.botania:flower.bubbellChibi.name=Bubbell Petite
tile.botania:flower.bubbellChibi.reference=And whistle
tile.botania:flower.solegnolia.name=Solegnolia
tile.botania:flower.solegnolia.reference=All your magnets are belong to us
tile.botania:flower.solegnoliaChibi.name=Solegnolia Petite
tile.botania:flower.solegnoliaChibi.reference=All your magnets are belong to us
 */

/*

item.botania:lexicon.name=Lexica Botania
item.botania:lexicon.bevo=Lexica Botana
item.botania:lexicon.saice=Lexica Botonia
item.botania:petal0.name=Mystical White Petal
item.botania:petal1.name=Mystical Orange Petal
item.botania:petal2.name=Mystical Magenta Petal
item.botania:petal3.name=Mystical Light Blue Petal
item.botania:petal4.name=Mystical Yellow Petal
item.botania:petal5.name=Mystical Lime Petal
item.botania:petal6.name=Mystical Pink Petal
item.botania:petal7.name=Mystical Gray Petal
item.botania:petal8.name=Mystical Light Gray Petal
item.botania:petal9.name=Mystical Cyan Petal
item.botania:petal10.name=Mystical Purple Petal
item.botania:petal11.name=Mystical Blue Petal
item.botania:petal12.name=Mystical Brown Petal
item.botania:petal13.name=Mystical Green Petal
item.botania:petal14.name=Mystical Red Petal
item.botania:petal15.name=Mystical Black Petal
item.botania:dye0.name=Floral White Powder
item.botania:dye1.name=Floral Orange Powder
item.botania:dye2.name=Floral Magenta Powder
item.botania:dye3.name=Floral Light Blue Powder
item.botania:dye4.name=Floral Yellow Powder
item.botania:dye5.name=Floral Lime Powder
item.botania:dye6.name=Floral Pink Powder
item.botania:dye7.name=Floral Gray Powder
item.botania:dye8.name=Floral Light Gray Powder
item.botania:dye9.name=Floral Cyan Powder
item.botania:dye10.name=Floral Purple Powder
item.botania:dye11.name=Floral Blue Powder
item.botania:dye12.name=Floral Brown Powder
item.botania:dye13.name=Floral Green Powder
item.botania:dye14.name=Floral Red Powder
item.botania:dye15.name=Floral Black Powder
item.botania:pestleAndMortar.name=Pestle and Mortar
item.botania:twigWand.name=Wand of the Forest
item.botania:manasteel.name=Manasteel Ingot
item.botania:manaPearl.name=Mana Pearl
item.botania:manaDiamond.name=Mana Diamond
item.botania:lensNormal.name=Mana Lens
item.botania:lensSpeed.name=Mana Lens: Velocity
item.botania:lensSpeed.short=Velocity
item.botania:lensPower.name=Mana Lens: Potency
item.botania:lensPower.short=Potency
item.botania:lensTime.name=Mana Lens: Resistance
item.botania:lensTime.short=Resistance
item.botania:lensEfficiency.name=Mana Lens: Efficiency
item.botania:lensEfficiency.short=Efficiency
item.botania:lensBounce.name=Mana Lens: Bounce
item.botania:lensBounce.short=Bounce
item.botania:lensGravity.name=Mana Lens: Gravity
item.botania:lensGravity.short=Gravity
item.botania:lensMine.name=Mana Lens: Bore
item.botania:lensMine.short=Bore
item.botania:lensDamage.name=Mana Lens: Damaging
item.botania:lensDamage.short=Damaging
item.botania:lensPhantom.name=Mana Lens: Phantom
item.botania:lensPhantom.short=Phantom
item.botania:lensMagnet.name=Mana Lens: Magnetizing
item.botania:lensMagnet.short=Magnetizing
item.botania:lensExplosive.name=Mana Lens: Entropic
item.botania:lensExplosive.short=Entropic
item.botania:lensInfluence.name=Mana Lens: Influence
item.botania:lensInfluence.short=Influence
item.botania:lensWeight.name=Mana Lens: Weight
item.botania:lensWeight.short=Weight
item.botania:lensPaint.name=Mana Lens: Paintslinger
item.botania:lensPaint.short=Paintslinger
item.botania:lensFire.name=Mana Lens: Kindle
item.botania:lensFire.short=Kindle
item.botania:lensPiston.name=Mana Lens: Force
item.botania:lensPiston.short=Force
item.botania:lensLight.name=Mana Lens: Flash
item.botania:lensLight.short=Flash
item.botania:lensWarp.name=Mana Lens: Warp
item.botania:lensWarp.short=Warp
item.botania:lensRedirect.name=Mana Lens: Redirective
item.botania:lensRedirect.short=Redirective
item.botania:lensFirework.name=Mana Lens: Celebratory
item.botania:lensFirework.short=Celebratory
item.botania:lensFlare.name=Mana Lens: Flare
item.botania:lensFlare.short=Flare
item.botania:rune0.name=Rune of Water
item.botania:rune1.name=Rune of Fire
item.botania:rune2.name=Rune of Earth
item.botania:rune3.name=Rune of Air
item.botania:rune4.name=Rune of Spring
item.botania:rune5.name=Rune of Summer
item.botania:rune6.name=Rune of Autumn
item.botania:rune7.name=Rune of Winter
item.botania:rune8.name=Rune of Mana
item.botania:rune9.name=Rune of Lust
item.botania:rune10.name=Rune of Gluttony
item.botania:rune11.name=Rune of Greed
item.botania:rune12.name=Rune of Sloth
item.botania:rune13.name=Rune of Wrath
item.botania:rune14.name=Rune of Envy
item.botania:rune15.name=Rune of Pride
item.botania:signalFlare.name=Signal Flare
item.botania:manaTablet.name=Mana Tablet
item.botania:manaGun.name=Mana Blaster
item.botania:compositeLens.name=Composite Mana Lens: %s %s
item.botania:manaCookie.name=Biscuit of Totality
item.botania:fertilizer.name=Floral Fertilizer
item.botania:grassSeeds0.name=Pasture Seeds
item.botania:grassSeeds1.name=Boreal Seeds
item.botania:grassSeeds2.name=Infestation Spores
item.botania:grassSeeds3.name=Dry Pasture Seeds
item.botania:grassSeeds4.name=Golden Pasture Seeds
item.botania:grassSeeds5.name=Vivid Pasture Seeds
item.botania:grassSeeds6.name=Scorched Pasture Seeds
item.botania:grassSeeds7.name=Infused Pasture Seeds
item.botania:grassSeeds8.name=Mutated Pasture Seeds
item.botania:livingwoodTwig.name=Livingwood Twig
item.botania:dirtRod.name=Rod of the Lands
item.botania:terraformRod.name=Rod of the Terra Firma
item.botania:manaMirror.name=Mana Mirror
item.botania:manasteelHelm.name=Manasteel Helmet
item.botania:manasteelChest.name=Manasteel Chestplate
item.botania:manasteelLegs.name=Manasteel Leggings
item.botania:manasteelBoots.name=Manasteel Boots
item.botania:manasteelPick.name=Manasteel Pickaxe
item.botania:manasteelShovel.name=Manasteel Shovel
item.botania:manasteelAxe.name=Manasteel Axe
item.botania:manasteelSword.name=Manasteel Sword
item.botania:manasteelShears.name=Manasteel Shears
item.botania:grassHorn0.name=Horn of the Wild
item.botania:grassHorn1.name=Horn of the Canopy
item.botania:grassHorn2.name=Horn of the Covering
item.botania:terrasteel.name=Terrasteel Ingot
item.botania:terrasteelHelm.name=Terrasteel Helmet
item.botania:terrasteelChest.name=Terrasteel Chestplate
item.botania:terrasteelLegs.name=Terrasteel Leggings
item.botania:terrasteelBoots.name=Terrasteel Boots
item.botania:terraSword.name=Terra Blade
item.botania:tinyPlanet.name=Tiny Planet
item.botania:manaRing.name=Band of Mana
item.botania:auraRing.name=Band of Aura
item.botania:manaRingGreater.name=Greater Band of Mana
item.botania:auraRingGreater.name=Greater Band of Aura
item.botania:travelBelt.name=Soujourner's Sash
item.botania:knockbackBelt.name=Tectonic Girdle
item.botania:icePendant.name=Snowflake Pendant
item.botania:lavaPendant.name=Pyroclast Pendant
item.botania:lifeEssence.name=Gaia Spirit
item.botania:goldenLaurel.name=Golden Laurel Crown
item.botania:redstoneRoot.name=Redstone Root
item.botania:magnetRing.name=Ring of Magnetization
item.botania:waterRing.name=Ring of Chordata
item.botania:miningRing.name=Ring of the Mantle
item.botania:reachRing.name=Ring of Far Reach
item.botania:terraPick.name=Terra Shatterer
item.botania:divaCharm.name=Charm of the Diva
item.botania:flightTiara.name=Flügel Tiara
item.botania:enderDagger.name=Soulscribe
item.botania:quartz0.name=Smokey Quartz
item.botania:quartz1.name=Mana Quartz
item.botania:quartz2.name=Blaze Quartz
item.botania:quartz3.name=Lavender Quartz
item.botania:quartz4.name=Redquartz
item.botania:quartz5.name=Elven Quartz
item.botania:quartz6.name=Sunny Quartz
item.botania:elementium.name=Elementium Ingot
item.botania:pixieDust.name=Pixie Dust
item.botania:dragonstone.name=Dragonstone
item.botania:waterRod.name=Rod of the Seas
item.botania:elementiumHelm.name=Elementium Helmet
item.botania:elementiumChest.name=Elementium Chestplate
item.botania:elementiumLegs.name=Elementium Leggings
item.botania:elementiumBoots.name=Elementium Boots
item.botania:elementiumPick.name=Elementium Pickaxe
item.botania:elementiumShovel.name=Elementium Shovel
item.botania:elementiumAxe.name=Elementium Axe
item.botania:elementiumSword.name=Elementium Sword
item.botania:elementiumShears.name=Elementium Shears
item.botania:openBucket.name=Extrapolated Bucket
item.botania:spawnerMover.name=Life Aggregator
item.botania:pixieRing.name=Great Fairy Ring
item.botania:superTravelBelt.name=Globetrotter's Sash
item.botania:rainbowRod.name=Rod of the Bifrost
item.botania:tornadoRod.name=Rod of the Skies
item.botania:fireRod.name=Rod of the Hells
item.botania:vineBall.name=Vine Ball
item.botania:slingshot.name=Livingwood Slingshot
item.botania:manaBottle.name=Mana in a Bottle
item.botania:prismarineShard.name=Prismarine Shard
item.botania:laputaShard.name=Shard of Laputa
item.botania:virus0.name=Necrodermal Virus
item.botania:virus1.name=Nullodermal Virus
item.botania:skyDirtRod.name=Rod of the Highlands
item.botania:placeholder.name=Crafting Placeholder
item.botania:manasteelHelmReveal.name=Manasteel Helmet of Revealing
item.botania:terrasteelHelmReveal.name=Terrasteel Helmet of Revealing
item.botania:elementiumHelmReveal.name=Elementium Helmet of Revealing
item.botania:itemFinder.name=The Spectator
item.botania:superLavaPendant.name=Crimson Pendant
item.botania:enderHand.name=Hand of Ender
item.botania:glassPick.name=Vitreous Pickaxe
item.botania:spark.name=Spark
item.botania:sparkUpgrade0.name=Spark Augment: Dispersive
item.botania:sparkUpgrade1.name=Spark Augment: Dominant
item.botania:sparkUpgrade2.name=Spark Augment: Recessive
item.botania:sparkUpgrade3.name=Spark Augment: Isolated
item.botania:diviningRod.name=Rod of the Plentiful Mantle
item.botania:gravityRod.name=Rod of the Shaded Mesa
item.botania:regenIvy.name=Timeless Ivy
item.botania:manaInkwell.name=Botanurgist's Inkwell
item.botania:vial0.name=Managlass Vial
item.botania:vial1.name=Alfglass Flask
item.botania:brewVial.name=Vial of %s (%s)
item.botania:brewFlask.name=Flask of %s (%s)
item.botania:bloodPendant.name=Tainted Blood Pendant
item.botania:redString.name=Red String
item.botania:missileRod.name=Rod of the Unstable Reservoir
item.botania:holyCloak.name=Cloak of Virtue
item.botania:unholyCloak.name=Cloak of Sin
item.botania:craftingHalo.name=Assembly Halo
item.botania:autocraftingHalo.name=Manufactory Halo
item.botania:blackLotus0.name=Black Lotus
item.botania:blackLotus1.name=Blacker Lotus
item.botania:dreamwoodTwig.name=Dreamwood Twig
item.botania:monocle.name=Manaseer Monocle
item.botania:clip.name=Lens Clip
item.botania:cobbleRod.name=Rod of the Depths
item.botania:smeltRod.name=Rod of the Molten Core
item.botania:worldSeed.name=World Seed
item.botania:spellCloth.name=Spellbinding Cloth
item.botania:thornChakram0.name=Thorn Chakram
item.botania:thornChakram1.name=Flare Chakram
item.botania:overgrowthSeed.name=Overgrowth Seed
item.botania:craftPattern0.name=Crafting Pattern #1: 1x1
item.botania:craftPattern1.name=Crafting Pattern #2: 2x2
item.botania:craftPattern2.name=Crafting Pattern #3: 1x2
item.botania:craftPattern3.name=Crafting Pattern #4: 2x1
item.botania:craftPattern4.name=Crafting Pattern #5: 1x3
item.botania:craftPattern5.name=Crafting Pattern #6: 3x1
item.botania:craftPattern6.name=Crafting Pattern #7: 2x3
item.botania:craftPattern7.name=Crafting Pattern #8: 3x2
item.botania:craftPattern8.name=Crafting Pattern #9: Donut
item.botania:gaiaIngot.name=Gaia Spirit Ingot
item.botania:ancientWill0.name=Will of Ahrim
item.botania:ancientWill1.name=Will of Dharok
item.botania:ancientWill2.name=Will of Guthan
item.botania:ancientWill3.name=Will of Torag
item.botania:ancientWill4.name=Will of Verac
item.botania:ancientWill5.name=Will of Karil
item.botania:corporeaSpark0.name=Corporea Spark
item.botania:corporeaSpark1.name=Master Corporea Spark
item.botania:enderAirBottle.name=Ender Air Bottle
item.botania:livingwoodBow.name=Livingwood Bow
item.botania:crystalBow.name=Crystal Bow
item.botania:cosmetic0.name=Black Bowtie
item.botania:cosmetic1.name=Black Tie
item.botania:cosmetic2.name=Red Glasses
item.botania:cosmetic3.name=Puffy Scarf
item.botania:cosmetic4.name=Engineer Goggles
item.botania:cosmetic5.name=Eyepatch
item.botania:cosmetic6.name=Wicked Eyepatch
item.botania:cosmetic7.name=Red Ribbons
item.botania:cosmetic8.name=Pink Flower Bud
item.botania:cosmetic9.name=Polka-Dotted Bows
item.botania:cosmetic10.name=Blue Butterfly
item.botania:cosmetic11.name=Cat Ears
item.botania:cosmetic12.name=Witch Pin
item.botania:cosmetic13.name=Devil Tail
item.botania:cosmetic14.name=Kamui Eye
item.botania:cosmetic15.name=Googly Eyes
item.botania:cosmetic16.name=Four-Leafed Clover
item.botania:cosmetic17.name=Clock Eye
item.botania:cosmetic18.name=Unicorn Horn
item.botania:cosmetic19.name=Devil Horns
item.botania:cosmetic20.name=Hyper Plus
item.botania:cosmetic21.name=Botanist Emblem
item.botania:cosmetic22.name=Ancient Mask
item.botania:cosmetic23.name=Eerie Mask
item.botania:cosmetic24.name=Alien Antenna
item.botania:cosmetic25.name=Anaglyph Glasses
item.botania:cosmetic26.name=Orange Shades
item.botania:cosmetic27.name=Groucho Glasses
item.botania:cosmetic28.name=Thick Eyebrows
item.botania:cosmetic29.name=Lusitanic Shield
item.botania:cosmetic30.name=Tiny Potato Mask
item.botania:cosmetic31.name=Questgiver Mark
item.botania:manaString.name=Mana Infused String
item.botania:swapRing.name=Ring of Correction
item.botania:flowerBag.name=Flower Pouch
item.botania:phantomInk.name=Phantom Ink
item.botania:poolMinecart.name=Minecart with Mana Pool
item.botania:pinkinator.name=The Pinkinator
item.botania:infiniteFruit.name=The Fruit of Grisaia
item.botania:kingKey.name=Key of the King's Law
item.botania:flugelEye.name=Eye of the Flügel
item.botania:thorRing.name=Ring of Thor
item.botania:odinRing.name=Ring of Odin
item.botania:lokiRing.name=Ring of Loki
item.botania:aesirRing.name=Ring of the Aesir
item.botania:dice.name=Dice of Fate
item.botania:keepIvy.name=Resolute Ivy
item.botania:blackHoleTalisman.name=Black Hole Talisman
item.botania:recordGaia1.name=Scathed Music Disc
item.botania:recordGaia2.name=Scathed Music Disc
item.botania:temperanceStone.name=Stone of Temperance
item.botania:incenseStick.name=Incense Stick
item.botania:terraAxe.name=Terra Truncator
item.botania:manasteelNugget.name=Manasteel Nugget
item.botania:terrasteelNugget.name=Terrasteel Nugget
item.botania:elementiumNugget.name=Elementium Nugget
item.botania:root.name=Living Root
item.botania:pebble.name=Pebble
item.botania:waterBowl.name=Bowl of Water
item.botania:obedienceStick.name=Floral Obedience Stick
item.botania:cacophonium.name=Cacophonium
item.botania:slimeBottle.name=Slime in a Bottle
item.botania:starSword.name=Starcaller
item.botania:exchangeRod.name=Rod of the Shifting Crust
item.botania:magnetRingGreater.name=Greater Ring of Magnetization
item.botania:thunderSword.name=Thundercaller
item.botania:manaweaveCloth.name=Manaweave Cloth
item.botania:manaweaveHelm.name=Manaweave Cowl
item.botania:manaweaveChest.name=Manaweave Robe Top
item.botania:manaweaveLegs.name=Manaweave Robe Bottom
item.botania:manaweaveBoots.name=Manaweave Boots
item.botania:santaweaveHelm.name=Santaweave Cowl
item.botania:santaweaveChest.name=Santaweave Robe Top
item.botania:santaweaveLegs.name=Santaweave Robe Bottom
item.botania:santaweaveBoots.name=Santaweave Boots
item.botania:gaiaHead.name=Gaia Guardian's Head
item.botania:sextant.name=Worldshaper's Sextant
item.botania:speedUpBelt.name=Planestrider's Sash
item.botania:baubleBox.name=Bauble Case
item.botania:manaPowder.name=Mana Powder


 */
